### ISSUE TITLE
Scrolling throws exception

### ISSUE THREAD

**Issue by alirezaaa** [alirezaaa/TimelinePostContainer#2]
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.widget.ProgressBar.getParent()' on a null object reference
>                                                                          at com.github.alirezaaa.timelinepostcontainer.TimelinePostContainer.addProgressBar(TimelinePostContainer.java:359)
>                                                                          at com.github.alirezaaa.timelinepostcontainer.TimelinePostContainer.createImageView(TimelinePostContainer.java:174)
>                                                                          at com.github.alirezaaa.timelinepostcontainer.TimelinePostContainer.onDetachedFromWindow(TimelinePostContainer.java:293)

**Comment by alirezaaa** [comment]
Fixed on `dev-2.1` branch.
